name: Elk-Stack-Implementation


services:
  kibana:
    image: kibana:9.0.2
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - elk-stack
    volumes:
      - kibana_data:/usr/share/kibana/data
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    mem_limit: 1000000
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=kibana

  elasticsearch:
    image: elasticsearch:9.0.2
    containter_name: elasticsearch
    ports:
      - "9200:9200"
    networks:
      - elk-stack
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    mem_limit: 1000000
    environment:
      - cluster.name=thebestname
      - network.host=0.0.0.0
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ELASTIC_PASSWORD=elastic
      - discovery.type=single-node


  logstash:
    image: logstash:9.0.2
    container_name: logstash
    ports:
      - "5044:5044"
    networks:
      - elk-stack
    volumes:
      - log_data:/usr/share/logstash/data
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    mem_limit: 1000000
    environment:
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=elastic
      - ELASTIC_HOSTS=http://elasticsearch:9200
      - http.host=0.0.0.0

networks:
  elk-stack:

volumes:
  kibana_data:
  elastic_data:
  log_data:


    
